### ISSUE TITLE
Make CLI arguments optional

### ISSUE THREAD

**Issue by 0xPhaze** [crytic/fuzz-utils#39]
### Describe the desired feature

Can any of the CLI arguments be optional by using defaults?
I'd be happy just specifying `fuzz-utils contracts/Contract.sol` and it running with it

- Can `-cd` default to `.corpus` or some other?
- Can `-c` be inferred if there is one main contract defined in the specified target?
- Can `-td` be `test`?
- Can `-f` default to either `echidna`/`medusa`? Preferably medusa
- Can `-i` be inferred, since the target and test directory are given

**Comment by tuturu-tech** [comment]
Resolved with PR https://github.com/crytic/fuzz-utils/pull/43
